### ISSUE TITLE
How to ignore logging messages in IPython/Jupyter

### ISSUE THREAD

**Issue by deeplook** [danmichaelo/mwtemplates#6] opened 2016-03-10 15:14 UTC
I'm getting lots of these messages, slowing down execution a lot, but only in the interactive Python/Jupyter notebooks, not in `ipython` sessions:

```
DEBUG:root: <template><title>IPAc-en</title>
DEBUG:root:- Popping from stack: ...}}
DEBUG:root:  [  97] Advancing pointer until: [{<}|
DEBUG:root:  [  97] Found literal section of length 1: "
```

I can easily filter other ones like those by `requests`, but I fail to filter those by `mwtemplates` and wonder if it could be mentioned on the README, maybe, how to do that? In any case this doesn't remove the messages spit out by `mwtemplates`:

```
import logging
logging.getLogger("requests").setLevel(logging.ERROR)
logging.getLogger("mwtemplates.preprocessor").setLevel(logging.ERROR)
```

**Comment by danmichaelo** [comment] 2016-03-13 17:58
Hm, I'm not able to reproduce this: https://gist.github.com/danmichaelo/c6b7d20852a584e0e719

But perhaps this was fixed by some of the commits I've done since the last release (0.3.4), like https://github.com/danmichaelo/mwtemplates/commit/8804ba44ee86a57294f84b8f27de904b6f52838a .

I've pushed a new release (0.4.0) now, bringing the PyPI version up to date with the GitHub master version. If you installed `mwtemplates` from PyPI (using pip or similar), please try `pip install -U mwtemplates` and see if that fixes the problem.

**Closed** 2018-02-01 23:20 UTC
